import asyncio
import os
import httpx
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv('/Users/rohithp/Desktop/Hello_Guard_Voice_AI/gard-backend/.env')

URI = os.getenv('MONGODB_URI')
DB_NAME = os.getenv('MONGODB_DATABASE', 'hellogard_db')
API_KEY = os.getenv('LYZR_API_KEY')
VOICE_BASE = os.getenv('LYZR_VOICE_BASE', 'https://voice-livekit.studio.lyzr.ai/v1')

async def main():
    client = AsyncIOMotorClient(URI)
    db = client[DB_NAME]
    
    print("1. Looking for latest transcript in DB...")
    # Find the latest transcript (sorting by timestamp descending)
    latest_transcript = await db["transcripts"].find_one({}, sort=[("timestamp", -1)])
    
    if not latest_transcript:
        print("No transcripts found in database.")
        return
        
    session_id = latest_transcript.get('sessionId') or latest_transcript.get('session_id')
    print(f"Latest conversation Session ID: {session_id}")
    
    print(f"\n2. Attempting to fetch audio from Lyzr API for {session_id}...")
    audio_url = f"{VOICE_BASE}/transcripts/{session_id}/audio"
    
    async with httpx.AsyncClient() as http_client:
        resp = await http_client.get(
            audio_url,
            headers={"x-api-key": API_KEY},
            timeout=10.0
        )
        
        print(f"Lyzr API Response Status: {resp.status_code}")
        
        if resp.status_code == 200:
            content_type = resp.headers.get('Content-Type')
            content_length = len(resp.content)
            print(f"✅ Success! Received {content_length} bytes of audio ({content_type}).")
            
            print("\n3. Saving to our local call_audios collection...")
            from bson.binary import Binary
            from datetime import datetime
            
            # Check if it already exists
            existing = await db["call_audios"].find_one({"session_id": session_id})
            if existing:
                print("Audio already exists in our DB, updating it.")
                await db["call_audios"].update_one(
                    {"session_id": session_id},
                    {"$set": {"audio_data": Binary(resp.content), "content_type": content_type}}
                )
            else:
                print("Inserting new audio document.")
                await db["call_audios"].insert_one({
                    "session_id": session_id,
                    "audio_data": Binary(resp.content),
                    "content_type": content_type,
                    "created_at": datetime.now().isoformat()
                })
            print("✅ MongoDB save completed successfully.")
        else:
            print(f"❌ Failed to fetch. Message: {resp.text}")
            print("\nNote: This is expected if 'session_id' was generated by a mock data script and isn't a real LiveKit call on the Lyzr platform.")

if __name__ == "__main__":
    asyncio.run(main())
